version: "3.8"

services:
  php:
    build:
      context: .
      target: dev
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - booking_net

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.3}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS:-root}
      MYSQL_DATABASE: ${MYSQL_DB:-booking}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASS:-user}
    volumes:
      - ./volumes/database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/Caddyfile:/etc/caddy/Caddyfile
      - ./public/:/app/public/
    networks:
      - booking_net

networks:
  booking_net:
    driver: bridge